using System.ComponentModel.DataAnnotations;

namespace BookHubApi.Models
{
    public class Book
    {
        public int Id { get; set; }  // Auto-generated by DB

        [Required]
        public string Title { get; set; } = string.Empty;

        [Required]
        public string Author { get; set; } = string.Empty;

        [Range(1, 100000)]
        public decimal Price { get; set; }
    }
}
